### ISSUE TITLE
Sporadic `IdealGas` failures

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#225]
Not sure what's going on here, but I've seen some ideal gas failures (e.g. [here](https://travis-ci.org/choderalab/openmmtools/jobs/243296977)):
```
======================================================================
FAIL: Testing MCMC expectation for IdealGas
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/openmmtools-0.11.1-py3.5.egg/openmmtools/tests/test_mcmc.py", line 180, in subtest_mcmc_expectation
    assert nsigma <= NSIGMA_CUTOFF, err_msg.format()
AssertionError: Volume expectation
observed 9520.04085 +-   98.87442kT | expected 8811.36331 | error  708.67754 +-   98.87442 (7.2 sigma)
----------------------------------------------------------------------------
```

**Comment by jchodera** [comment]
This doesn't appear to be failing anymore, so closing.
