### ISSUE TITLE
ContextCache doing something weird to systems?

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/openmmtools#268]
I have hybrid systems 
[hybrid_fail.xml.zip](https://github.com/choderalab/openmmtools/files/1218966/hybrid_fail.xml.zip)
 that work fine when they are used in a regular context creation, but on context creation with the ContextCache, I get an odd error (below). Immediately below is the code you can use to reproduce this condition, combined with the (unzipped) attached file.

```python
import simtk.openmm as openmm
import simtk.openmm.app as app
import simtk.unit as unit
import openmmtools.cache as cache
import openmmtools.states as states

#this code works
sys_file = open('hybrid_fail.xml', 'r')
sys_string = "".join(sys_file.readlines())
sys_file.close()
system = openmm.XmlSerializer.deserialize(sys_string)
integrator = openmm.VerletIntegrator(1.0)
platform = openmm.Platform.getPlatformByName("CPU")
ctx1 = openmm.Context(system, integrator, platform)

del ctx1, integrator, system

#now try the same with the context cache
system = openmm.XmlSerializer.deserialize(sys_string)
integrator = openmm.VerletIntegrator(1.0)
platform = openmm.Platform.getPlatformByName("CPU")
t_state = states.ThermodynamicState(system, temperature=300.0*unit.kelvin, pressure=1.0*unit.atmosphere)

ctx_cache = cache.ContextCache(platform=platform)

#this fails with an error about exclusions
ctx2, integrator2 = ctx_cache.get_context(t_state, integrator)
```

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd_comm.py", line 1074, in doIt
    result = pydevd_vars.evaluateExpression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd_vars.py", line 350, in evaluateExpression
    Exec(expression, updated_globals, frame.f_locals)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 6, in <module>
  File "/Users/grinawap/anaconda/lib/python3.5/site-packages/openmmtools-0.11.3-py3.5.egg/openmmtools/cache.py", line 404, in get_context
    context = thermodynamic_state.create_context(integrator, self._platform)
  File "/Users/grinawap/anaconda/lib/python3.5/site-packages/openmmtools-0.11.3-py3.5.egg/openmmtools/states.py", line 819, in create_context
    return openmm.Context(system, integrator, platform)
  File "/Users/grinawap/anaconda/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 6269, in __init__
    this = _openmm.new_Context(*args)
Exception: All Forces must have identical exclusions
```

**Comment by andrrizzi** [comment]
Weird! It could be something happening in `ThermodynamicState` rather than in `ContextCache`. Neither of those classes should touch the system nonbonded forces or particles if I remember correctly though.

I tried to reproduce this but I got a different error. With the latest `openmm` from the `main` label (I have `7.1.1`), I get
```
Traceback (most recent call last):
  File "prova.py", line 11, in <module>
    system = openmm.XmlSerializer.deserialize(sys_string)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 18955, in deserialize
    return XmlSerializer.deserializeSystem(inputString)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 18799, in deserializeSystem
    return _openmm.XmlSerializer_deserializeSystem(inputString)
Exception: Unsupported version number
```
What openmm version are you using?

**Comment by pgrinaway** [comment]
Oops, looks like that ran with `'7.1.0.dev-9f6bd49'`

**Comment by pgrinaway** [comment]
Sorry, this was me misreading the stacktrace I originally posted. Nothing to do with `ContextCache` or `ThermodynamicState`... it's a requirement only enforced by some platforms (`CPU` at least).

**Comment by jchodera** [comment]
Inconsistent exceptions are often a sign something is wrong in your alchemical factory.
