### ISSUE TITLE
UreyBradley term in CharmmPsfFile not recognized by alchemy.py

### ISSUE THREAD

**Issue by SimoneCnt** [choderalab/openmmtools#296]
I'm trying to so some alchemical transformations using alchemy.py for my system generated using CharmmPsfFile. 
When I call ```get_energy_components()``` I get this error:

```
Traceback (most recent call last):
  File "./runomm.py", line 283, in <module>
    alch_ener = alch_factory.get_energy_components(alch_system, alch_state, positions)
  File "/home/simone/opt/app/openmm/7.1mod/lib/python3.6/site-packages/openmmtools-0.13.2-py3.6.egg/openmmtools/alchemy.py", line 876, in get_energy_components
    force_labels = cls._find_force_components(alchemical_system)
  File "/home/simone/opt/app/openmm/7.1mod/lib/python3.6/site-packages/openmmtools-0.13.2-py3.6.egg/openmmtools/alchemy.py", line 1999, in _find_force_components
    add_label('unmodified ' + force.__class__.__name__, force_index)
  File "/home/simone/opt/app/openmm/7.1mod/lib/python3.6/site-packages/openmmtools-0.13.2-py3.6.egg/openmmtools/alchemy.py", line 1947, in add_label
    assert label not in force_labels
AssertionError
```

Looking around in the code, I found this
```
forces = {system.getForce(index).__class__.__name__: system.getForce(index)
        for index in range(system.getNumForces())}
```
which fails for the UreyBradley energy terms as both the normal bonds and the UreyBradley have the same ```HarmonicBondForce``` name.

If in ```CharmmPsfFile``` I comment out all code relative to the UreyBradley energy, then everything seems to work in alchemy.py.

How can this be fixed?

**Comment by jchodera** [comment]
Thanks for catching this! We certainly don't want to be using a `dict` based on class name---we'll have to rework that logic.

@andrrizzi : Can you tackle this when you have a chance?

**Comment by andrrizzi** [comment]
> Can you tackle this when you have a chance?

Of course!
