### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#335]
Not sure how we missed this, but see the failures [here](https://travis-ci.org/choderalab/openmmtools/jobs/347651589#L3360-L3380).
```
======================================================================
FAIL: Doctest: openmmtools.integrators.ThermostatedIntegrator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for openmmtools.integrators.ThermostatedIntegrator
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/openmmtools-0.14.1-py2.7.egg/openmmtools/integrators.py", line 227, in ThermostatedIntegrator
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/openmmtools-0.14.1-py2.7.egg/openmmtools/integrators.py", line 283, in openmmtools.integrators.ThermostatedIntegrator
Failed example:
    integrator.getTemperature()
Expected:
    Traceback (most recent call last):
    ...
    AttributeError: type object 'object' has no attribute '__getattr__'
Got:
    Quantity(value=380.0, unit=kelvin)
```

**Comment by andrrizzi** [comment]
This is connected to the OpenMM 7.2 release. The doctest error is not a problem. We'll just have to update the example since now `Context.getIntegrator()` preserves the Python class.
