### ISSUE TITLE
pymbar not included as req in conda package

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openmmtools#428]
It looks like pymbar isn't getting recognized as a requirement for OpenMMTools when conda installs it. I see it in the conda recipe, but it didn't make it to the requirements (e.g., info/index.json in the tgz file [on anaconda.org](https://anaconda.org/omnia/openmmtools/files)).

You can verify the problem with the following:

```bash
conda create -n openmmtools-pymbar -c conda-forge -c omnia python=3.7 openmmtools=0.18.2
conda activate openmmtools-pymbar
python -c "import openmmtools"
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dwhs/miniconda3/envs/openmmtools-pymbar/lib/python3.7/site-packages/openmmtools/__init__.py", line 8, in <module>
    from openmmtools import testsystems, integrators, alchemy, mcmc, states, cache, utils, constants, forces, forcefactories, storage, multistate
  File "/Users/dwhs/miniconda3/envs/openmmtools-pymbar/lib/python3.7/site-packages/openmmtools/multistate/__init__.py", line 64, in <module>
    from openmmtools.multistate.multistatesampler import MultiStateSampler
  File "/Users/dwhs/miniconda3/envs/openmmtools-pymbar/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 44, in <module>
    from openmmtools.multistate.utils import SimulationNaNError
  File "/Users/dwhs/miniconda3/envs/openmmtools-pymbar/lib/python3.7/site-packages/openmmtools/multistate/utils.py", line 31, in <module>
    from pymbar import timeseries  # for statistical inefficiency analysis
ModuleNotFoundError: No module named 'pymbar'
```

From git blame, I see that pymbar was added to the conda recipe long before the most recent release, so I'm not sure why it was missed in the release.

**Comment by andrrizzi** [comment]
Thanks for catching this, @dwhswenson ! We added it among the repo's dependencies here when we added the MBAR analyzer, but it looks that change didn't make it to the `omnia-md/conda-recipes` recipe. I'll push a build-bump release.

**Comment by andrrizzi** [comment]
Build pushed on Anaconda. Thank you again!
