### ISSUE TITLE
Windows CI is currently failing

### ISSUE THREAD

**Issue by mjw99** [choderalab/openmmtools#567]
Currently seeing this error:

```
======================================================================
ERROR: Failure: ImportError (DLL load failed while importing _openmm: The specified module could not be found.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\openmmtools\openmmtools\openmmtools\testsystems.py", line 57, in <module>
    import openmm
  File "C:\Miniconda\envs\test\lib\site-packages\openmm\__init__.py", line 19, in <module>
    from openmm.openmm import *
  File "C:\Miniconda\envs\test\lib\site-packages\openmm\openmm.py", line 13, in <module>
    from . import _openmm
ImportError: DLL load failed while importing _openmm: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda\envs\test\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Miniconda\envs\test\lib\site-packages\nose\loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "C:\Miniconda\envs\test\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda\envs\test\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Miniconda\envs\test\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\Miniconda\envs\test\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\a\openmmtools\openmmtools\openmmtools\tests\test_alchemy.py", line 30, in <module>
    from openmmtools import testsystems, forces
  File "D:\a\openmmtools\openmmtools\openmmtools\__init__.py", line 8, in <module>
    from openmmtools import testsystems, integrators, alchemy, mcmc, states, cache, utils, constants, forces, forcefactories, storage, multistate
  File "D:\a\openmmtools\openmmtools\openmmtools\testsystems.py", line 61, in <module>
    from simtk import openmm
  File "C:\Miniconda\envs\test\lib\site-packages\simtk\__init__.py", line 1, in <module>
    import openmm
  File "C:\Miniconda\envs\test\lib\site-packages\openmm\__init__.py", line 19, in <module>
    from openmm.openmm import *
  File "C:\Miniconda\envs\test\lib\site-packages\openmm\openmm.py", line 13, in <module>
    from . import _openmm
ImportError: DLL load failed while importing _openmm: The specified module could not be found.
```

**Comment by mjw99** [comment]
In local testing, in a VM mock of the CI environment, I find that this occurs specifically with the conda package:
```
 conda-forge::3.8.13-h9a09f29_0_cpython
```
Conversely, the packages:
```
conda-forge::3.8.10-h7840368_2_cpython
main::python-3.8.13-h6244533_0
```
both work.
