### ISSUE TITLE
PhaseAnalyzer del causing error.

### ISSUE THREAD

**Issue by richardjgowers** [choderalab/openmmtools#633]
The delete operator on PhaseAnalyzer seems to be tripping up.  PR to follow

typical traceback below
```
OSError: /tmp/tmpyggicnli/c8c410b8-040b-480a-b0c8-8ff0ca0207f6/complex_rbfe.nc does not exist
DEBUG:mpiplus.mpiplus:Single node: executing <bound method MultiStateReporter.close of <openmmtools.multistate.multistatereporter.MultiStateReporter object at 0x7fbd785fcac0>>
Exception ignored in: <function PhaseAnalyzer.__del__ at 0x7fbdc6454f70>
Traceback (most recent call last):
  File "/home/richard/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 581, in __del__
    self.clear()
  File "/home/richard/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 1227, in clear
    super().clear()
  File "/home/richard/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 597, in clear
    self._invalidate_cache_values('reporter')
  File "/home/richard/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 780, in _invalidate_cache_values
    self._invalidate_cache_values(k)
  File "/home/richard/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 780, in _invalidate_cache_values
    self._invalidate_cache_values(k)
  File "/home/richard/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 780, in _invalidate_cache_values
    self._invalidate_cache_values(k)
  [Previous line repeated 1 more time]
  File "/home/richard/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 777, in _invalidate_cache_values
    self._computed_observables[observable] = None
AttributeError: 'MultiStateSamplerAnalyzer' object has no attribute '_computed_observables'
```

**Comment by mikemhenry** [comment]
We should probably catch the `AttributeError` in `_invalidate_cache_values` since (from https://stackoverflow.com/a/1481512) mentions

>However, there are valid use cases for __del__: e.g. if an object X references Y and also keeps a copy of Y reference in a global cache (cache['X -> Y'] = Y) then it would be polite for X.__del__ to also delete the cache entry.

Which looks like what we are doing here.

Also from the [docs](https://docs.python.org/3/reference/datamodel.html?highlight=__del__#object.__del__) it sounds like `__del__` " [is] called when the instance is about to be destroyed" so we really just be using context mangers if cleanup is important with an `__exit__` (or `finally` block) since it might not get called until the intrepter exits.
