### ISSUE TITLE
Multi-GPU HREMD trajectory output

### ISSUE THREAD

**Issue by Dan-Burns** [choderalab/openmmtools#642]
Hello,

I want to use multiple gpus with the ReplicaExchangeSampler and MultiStateReporter to produce trajectories for an HREMD simulation.  Although the system appears to get setup properly and the simulation starts, it seems not to produce a trajectory.

I realized after reading another post that the trajectory might be getting saved to the checkpoint file rather than the output.nc.  In either case, when I start the simulation both files are generated but never grow in size.  Part of the problem might be that I don't know how to properly extract the trajectory from the file.

I'd like to know how to run this correctly on multiple gpus - I'd be fine if I'm limited to a single node. I've tried with two gpus and just added 'mpirun -np 2' before calling the python script and again, I just get the files that don't change in size.

hremd.tar.gz has the conda environment .yml, the system xml, pdb, script, and latest .  I also have some error logs that were generated.

Thank you in advance for any help.

Dan

[errorlogs.tar.gz](https://github.com/choderalab/openmmtools/files/10180015/errorlogs.tar.gz)
[hremd.tar.gz](https://github.com/choderalab/openmmtools/files/10180016/hremd.tar.gz)

**Comment by ijpulidos** [comment]
When I try running your script I can see the simulation returns NaNs in the very first iteration for the first replica.

```
❯ python 2hwg_remd.py 
Warning: The openmmtools.multistate API is experimental and may change in future releases
Warning: The openmmtools.multistate API is experimental and may change in future releases
Please cite the following:

        Friedrichs MS, Eastman P, Vaidyanathan V, Houston M, LeGrand S, Beberg AL, Ensign DL, Bruns CM, and Pande VS. Accelerating molecular dynamic simulations on graphics processing unit. J. Comput. Chem. 30:864, 2009. DOI: 10.1002/jcc.21209
        Eastman P and Pande VS. OpenMM: A hardware-independent framework for molecular simulations. Comput. Sci. Eng. 12:34, 2010. DOI: 10.1109/MCSE.2010.27
        Eastman P and Pande VS. Efficient nonbonded interactions for molecular dynamics on a graphics processing unit. J. Comput. Chem. 31:1268, 2010. DOI: 10.1002/jcc.21413
        Eastman P and Pande VS. Constant constraint matrix approximation: A robust, parallelizable constraint method for molecular simulations. J. Chem. Theor. Comput. 6:434, 2010. DOI: 10.1021/ct900463w
Potential energy is NaN after 0 attempts of integration with move LangevinSplittingDynamicsMove Attempting a restart...
Potential energy is NaN after 1 attempts of integration with move LangevinSplittingDynamicsMove Attempting a restart...
Potential energy is NaN after 2 attempts of integration with move LangevinSplittingDynamicsMove Attempting a restart...
Potential energy is NaN after 3 attempts of integration with move LangevinSplittingDynamicsMove Trying to reinitialize Context as a last-resort restart attempt...
Potential energy is NaN after 4 attempts of integration with move LangevinSplittingDynamicsMove
Propagating replica 0 at state 0 resulted in a NaN!
The state of the system and integrator before the error were saved in nan-error-logs
Traceback (most recent call last):
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 1322, in _propagate_replica
    mcmc_move.apply(thermodynamic_state, sampler_state, context_cache=self.sampler_context_cache)
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/openmmtools/mcmc.py", line 1146, in apply
    super(LangevinDynamicsMove, self).apply(thermodynamic_state, sampler_state,
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/openmmtools/mcmc.py", line 750, in apply
    raise IntegratorMoveError(err_msg, self, context)
openmmtools.mcmc.IntegratorMoveError: Potential energy is NaN after 4 attempts of integration with move LangevinSplittingDynamicsMove

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lila/data/chodera/pulidoi/debugging/openmmtools/replex_files/2hwg_remd.py", line 75, in <module>
    simulation.run()
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 778, in run
    self._propagate_replicas()
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/openmmtools/utils.py", line 94, in _wrapper
    return func(*args, **kwargs)
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 1295, in _propagate_replicas
    propagated_states, replica_ids = mpiplus.distribute(self._propagate_replica, range(self.n_replicas),
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/mpiplus/mpiplus.py", line 512, in distribute
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/mpiplus/mpiplus.py", line 512, in <listcomp>
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/pulidoi/miniconda3/envs/openmmtools-642-temp/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 1333, in _propagate_replica
    raise SimulationNaNError(message)
openmmtools.multistate.utils.SimulationNaNError: Propagating replica 0 at state 0 resulted in a NaN!
The state of the system and integrator before the error were saved in nan-error-logs
```
I'm not familiar with your system so I may completely off here, but most commonly when it fails right in the first iteration it means that there is something going on with the initial structure, maybe it needs some minimization or refining before attempting the replica exchange?

**Comment by Dan-Burns** [comment]
The system was minimized and then simulated for 50 ns while the temperature gradually increased to 300K. The input coordinates for the script are from the pdb generated at the end of that simulation. It may be something related to my system but it seems like it should be good to go. 

The remd setup is mostly copied and pasted so odds are I'm making a mistake somewhere.

**Comment by ijpulidos** [comment]
It might be related to this issue https://github.com/choderalab/openmmtools/issues/643 which is in our roadmap.

**Comment by Dan-Burns** [comment]
Thank you! Do any of the OpenMMTools contributors have a repository with a good example of running HREMD and extracting trajectories?  I'd like to compare it to my script.

**Comment by Dan-Burns** [comment]
I guess it was an equilibration issue.  I moved this conversation to [#484](https://github.com/choderalab/openmmtools/issues/484) since it sounded similar.
