### ISSUE TITLE
MultiStateReporter bugs: NetCDF: Filter error: bad id or parameters or duplicate filter

### ISSUE THREAD

**Issue by lucl13** [choderalab/openmmtools#663]
Dear all,

I am running a basic example in paralleltempering.py. I got this error. Any ideas to fix it? 

Version info: openmm: 8.0, openmmtools: 0.21.5

```
from openmmtools import states, cache, constants
from openmmtools.multistate import ReplicaExchangeSampler, ReplicaExchangeAnalyzer, MultiStateReporter, ParallelTemperingSampler

from openmm import unit
from openmmtools import testsystems, states, mcmc
import tempfile
testsystem = testsystems.AlanineDipeptideImplicit()
import os


#Create thermodynamic states for parallel tempering with exponentially-spaced schedule.
n_replicas = 3  # Number of temperature replicas.
T_min = 298.0 * unit.kelvin  # Minimum temperature.
T_max = 600.0 * unit.kelvin  # Maximum temperature.
reference_state = states.ThermodynamicState(system=testsystem.system, temperature=T_min)
#Initialize simulation object with options. Run with a GHMC integrator.
move = mcmc.GHMCMove(timestep=2.0*unit.femtoseconds, n_steps=50)
simulation = ParallelTemperingSampler(mcmc_moves=move, number_of_iterations=2)
#Create simulation with its storage file (in a temporary directory) and run.
storage_path = tempfile.NamedTemporaryFile(delete=False).name + '.nc'
reporter = MultiStateReporter(storage_path, checkpoint_interval=10)
simulation.create(reference_state,
                  states.SamplerState(testsystem.positions),
                  reporter, min_temperature=T_min,
                  max_temperature=T_max, n_temperatures=n_replicas)
```

```
Warning: The openmmtools.multistate API is experimental and may change in future releases
Warning: The openmmtools.multistate API is experimental and may change in future releases
Please cite the following:

        Friedrichs MS, Eastman P, Vaidyanathan V, Houston M, LeGrand S, Beberg AL, Ensign DL, Bruns CM, and Pande VS. Accelerating molecular dynamic simulations on graphics processing unit. J. Comput. Chem. 30:864, 2009. DOI: 10.1002/jcc.21209
        Eastman P and Pande VS. OpenMM: A hardware-independent framework for molecular simulations. Comput. Sci. Eng. 12:34, 2010. DOI: 10.1109/MCSE.2010.27
        Eastman P and Pande VS. Efficient nonbonded interactions for molecular dynamics on a graphics processing unit. J. Comput. Chem. 31:1268, 2010. DOI: 10.1002/jcc.21413
        Eastman P and Pande VS. Constant constraint matrix approximation: A robust, parallelizable constraint method for molecular simulations. J. Chem. Theor. Comput. 6:434, 2010. DOI: 10.1021/ct900463w
        Chodera JD and Shirts MR. Replica exchange and expanded ensemble simulations as Gibbs multistate: Simple improvements for enhanced mixing. J. Chem. Phys., 135:194110, 2011. DOI:10.1063/1.3660669

Traceback (most recent call last):
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatereporter.py", line 1463, in _resolve_nc_path
    return nc_group.groups[path_split[-1]]
KeyError: 'options'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatereporter.py", line 1800, in _write_dict
    nc_variable = self._resolve_nc_path(path, storage_name)
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatereporter.py", line 1465, in _resolve_nc_path
    return nc_group.variables[path_split[-1]]
KeyError: 'options'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenlin/Downloads/charmm-gui-7880613325/openmm_tremd/test_bug.py", line 22, in <module>
    simulation.create(reference_state,
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/paralleltempering.py", line 173, in create
    super(ParallelTemperingSampler, self).create(thermodynamic_states, sampler_states, storage=storage, **kwargs)
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 606, in create
    self._initialize_reporter()
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 1182, in _initialize_reporter
    self._store_options()
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 1256, in _store_options
    self._reporter.write_dict('options', self.options)
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatereporter.py", line 1104, in write_dict
    self._write_dict(path, data, storage_name=storage_name)
  File "/home/chenlin/anaconda3/envs/openmm/lib/python3.10/site-packages/openmmtools/multistate/multistatereporter.py", line 1812, in _write_dict
    nc_variable = storage_nc.createVariable(path, variable_type,
  File "src/netCDF4/_netCDF4.pyx", line 2945, in netCDF4._netCDF4.Dataset.createVariable
  File "src/netCDF4/_netCDF4.pyx", line 4184, in netCDF4._netCDF4.Variable.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Filter error: bad id or parameters or duplicate filter
```

**Comment by lucl13** [comment]
Just tested. openmm: 7.7 and openmmtools: 0.21.5 works fine.

**Comment by mikemhenry** [comment]
@lucl13 Thanks for the bug report! We are just about cut a new release so we will get this fixed soon :tm: 

@ijpulidos can you take a look at this?

**Comment by mikemhenry** [comment]
@lucl13 can you include your full script that triggers this error? Thanks!

**Comment by lucl13** [comment]
> @lucl13 can you include your full script that triggers this error? Thanks!

Hi, thanks for your quick reply.

The full script is:
```
from openmmtools import states, cache, constants
from openmmtools.multistate import ReplicaExchangeSampler, ReplicaExchangeAnalyzer, MultiStateReporter, ParallelTemperingSampler

from openmm import unit
from openmmtools import testsystems, states, mcmc
import tempfile
testsystem = testsystems.AlanineDipeptideImplicit()
import os


#Create thermodynamic states for parallel tempering with exponentially-spaced schedule.
n_replicas = 3  # Number of temperature replicas.
T_min = 298.0 * unit.kelvin  # Minimum temperature.
T_max = 600.0 * unit.kelvin  # Maximum temperature.
reference_state = states.ThermodynamicState(system=testsystem.system, temperature=T_min)
#Initialize simulation object with options. Run with a GHMC integrator.
move = mcmc.GHMCMove(timestep=2.0*unit.femtoseconds, n_steps=50)
simulation = ParallelTemperingSampler(mcmc_moves=move, number_of_iterations=2)
#Create simulation with its storage file (in a temporary directory) and run.
storage_path = tempfile.NamedTemporaryFile(delete=False).name + '.nc'
reporter = MultiStateReporter(storage_path, checkpoint_interval=10)
simulation.create(reference_state,
                  states.SamplerState(testsystem.positions),
                  reporter, min_temperature=T_min,
                  max_temperature=T_max, n_temperatures=n_replicas)
```

And below is my full conda list:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alabaster                 0.7.12             pyhd3eb1b0_0  
anyio                     3.5.0           py310h06a4308_0  
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py310h7f8727e_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0          py310h06a4308_0  
babel                     2.11.0          py310h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1          py310h06a4308_0  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.3               hafa529b_0    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
cftime                    1.6.2           py310hde88566_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6           py310h06a4308_0  
comm                      0.1.2           py310h06a4308_0  
cryptography              39.0.1          py310h34c0648_0    conda-forge
cudatoolkit               11.8.0              h37601d7_11    conda-forge
curl                      7.88.1               hdc1c0ab_0    conda-forge
debugpy                   1.5.1           py310h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
docutils                  0.18.1          py310h06a4308_3  
entrypoints               0.4             py310h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
flit-core                 3.6.0              pyhd3eb1b0_0  
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h4df4325_101    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1           py310h06a4308_0  
ipykernel                 6.19.2          py310h2f386ee_0  
ipython                   8.10.0          py310h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jedi                      0.18.1          py310h06a4308_1  
jinja2                    3.1.2           py310h06a4308_0  
jpeg                      9e                   h0b41bf4_3    conda-forge
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.17.3          py310h06a4308_0  
jupyter_client            7.4.9           py310h06a4308_0  
jupyter_core              5.2.0           py310h06a4308_0  
jupyter_server            1.23.4          py310h06a4308_0  
jupyterlab                3.5.3           py310h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.19.0          py310h06a4308_0  
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.88.1               hdc1c0ab_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_5    conda-forge
libnetcdf                 4.9.1           nompi_h34a3ff0_101    conda-forge
libnghttp2                1.51.0               hff17c54_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvmlite                  0.39.1          py310h58363a5_1    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1           py310h7f8727e_0  
matplotlib-inline         0.1.6           py310h06a4308_0  
mdtraj                    1.9.7           py310h902c554_4    conda-forge
mistune                   0.8.4           py310h7f8727e_1000  
mpiplus                   v0.0.1          pyhd8ed1ab_1003    conda-forge
nbclassic                 0.5.2           py310h06a4308_0  
nbclient                  0.5.13          py310h06a4308_0  
nbconvert                 6.4.4           py310h06a4308_0  
nbformat                  5.7.0           py310h06a4308_0  
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.6           py310h06a4308_0  
netcdf4                   1.6.3           nompi_py310h0feb132_100    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.5.2           py310h06a4308_0  
notebook-shim             0.2.2           py310h06a4308_0  
numba                     0.56.4          py310ha5257ce_0    conda-forge
numexpr                   2.8.3           py310hf05e7a9_101    conda-forge
numpy                     1.23.5          py310h53a5b5f_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openmm                    8.0.0           py310h5728c26_0    conda-forge
openmmtools               0.21.5             pyhd8ed1ab_0    conda-forge
openssl                   3.1.0                h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py310h9b08913_0    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0  
parmed                    4.0.0           py310heca2aa9_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0  
pdbfixer                  1.8.1              pyh6c4a22f_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2           py310h06a4308_0  
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1          py310h06a4308_0  
prompt-toolkit            3.0.36          py310h06a4308_0  
psutil                    5.9.0           py310h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd3eb1b0_0  
pymbar                    3.1.1           py310hde88566_2    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.0          py310h7f8727e_0  
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.7.0           py310hb60b9b2_3    conda-forge
python                    3.10.9          he550d4f_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2          py310h06a4308_0  
python_abi                3.10                    3_cp310    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
pyzmq                     23.2.0          py310h6a678d5_0  
readline                  8.1.2                h0f457ee_0    conda-forge
reform                    0.1                      pypi_0    pypi
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1          py310h8deb116_0    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hbd366e4_2    conda-forge
sniffio                   1.2.0           py310h06a4308_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
soupsieve                 2.3.2.post1     py310h06a4308_0  
sphinx                    5.0.2           py310h06a4308_0  
sphinx_rtd_theme          0.4.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
stack_data                0.2.0              pyhd3eb1b0_0  
terminado                 0.17.1          py310h06a4308_0  
testpath                  0.6.0           py310h06a4308_0  
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1           py310h06a4308_0  
tornado                   6.2             py310h5eee18b_0  
traitlets                 5.7.1           py310h06a4308_0  
typing-extensions         4.4.0           py310h06a4308_0  
typing_extensions         4.4.0           py310h06a4308_0  
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py310h06a4308_1  
websocket-client          0.58.0          py310h06a4308_4  
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h2531618_0  
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by mikemhenry** [comment]
@lucl13 Can you also post the full trace back of the error? That will help me figure out where things are breaking.

Also you can try and install our development trunk with `pip install git+https://github.com/choderalab/openmmtools.git` and check to see if that solves the problem.

**Comment by lucl13** [comment]
> @lucl13 Can you also post the full trace back of the error? That will help me figure out where things are breaking.
> 
> Also you can try and install our development trunk with `pip install git+https://github.com/choderalab/openmmtools.git` and check to see if that solves the problem.

Tested. openmmtools 0.21.5+6.gfafd19a fixed the problem.

**Comment by mikemhenry** [comment]
@lucl13 Awesome! We will be getting a release out soon. Thank you for the very helpful bug report :heart:
